<?php

namespace App\Factory;

use App\Entity\Category;
use Zenstruck\Foundry\LazyValue;
use Zenstruck\Foundry\Persistence\PersistentProxyObjectFactory;

/**
 * @extends PersistentProxyObjectFactory<Category>
 */
final class CategoryFactory extends PersistentProxyObjectFactory
{
    /**
     * @see https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#factories-as-services
     *
     * @todo inject services if required
     */
    public function __construct()
    {
    }

    public static function class(): string
    {
        return Category::class;
    }

    /**
     * Defines the default values for the Category entity's attributes.
     * It uses a random word generated by Faker and formats it in title case
     * (first letter capitalized) using 'mb_convert_case' to ensure proper Unicode support.
     *
     * @return array|callable The defaults attributs for Category Entity
     */
    protected function defaults(): array|callable
    {
        return [
            'name' => LazyValue::new(fn () => mb_convert_case(self::faker()->word(), MB_CASE_TITLE, 'UTF-8')),
        ];
    }

    /**
     * @see https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#initialization
     */
    protected function initialize(): static
    {
        return $this
            // ->afterInstantiate(function(Category $category): void {})
        ;
    }
}
